on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, edited]
  workflow_dispatch:
  create:

jobs:
  linux-build:
    name: Wrapper Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp38-cp38", "cp39-cp39", "cp310-cp310", "cp311-cp311"] 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PYTHON_VERSION=${{ matrix.pyversion }} -v `pwd`:/home quay.io/pypa/manylinux_2_28_x86_64 /home/pypackage/build-wheel-linux.sh
        # cleanup for custom runner
        sudo chown -R $(whoami):$(whoami) .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: wheelhouse/