name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools
    - name: Build and install
      run: pip install --verbose .

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set script permissions
      run: chmod +x pypackage/build-wheels-linux.sh
    - name: Build and Repair Wheel in manylinux container
      run: |
        docker run -e PLAT=manylinux_2_28_x86_64 -e PYTHON_VERSIONS="3.7 3.8 3.9 3.10 3.11" -v $PWD:/io quay.io/pypa/manylinux_2_28_x86_64 /io/pypackage/build-wheels-linux.sh
    
    - name: Publish to PyPI
      run: |
        pip install twine
        twine upload wheelhouse/*manylinux*.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}